### ISSUE TITLE
Not in VSTS marketplace?

### ISSUE THREAD

**Issue by nneubauer** [johanclasson/vso-agent-tasks#1]
Hi, the dbup task is exactly what I was looking for, but unfortunatly I can not find the task/extension in the VSTS marketplace. Did you not publish there on purpose? I'd really love to see them there and spare me the copy/paste for all our builds.

**Comment by johanclasson** [comment]
Thanks for letting me know.

The marketplace was not released when I wrote these... Publishing them there is a great idea! But until I get time to do that you can install them manually with https://github.com/Microsoft/tfs-cli. I describe how in the [repository readme](https://github.com/johanclasson/vso-agent-tasks/blob/master/README.md).

**Comment by johanclasson** [comment]
I have now made an extension for the marketplace and Microsoft is now verifying my publisher request. Stay tuned! :)

**Comment by johanclasson** [comment]
It is now [live](https://marketplace.visualstudio.com/items?itemName=johanclasson.UpdateDatabaseWithDbUp).
