### ISSUE TITLE
ApplySemanticVersioningToAssemblies - 'Make Release' depending on Branch

### ISSUE THREAD

**Issue by Franklin89** [johanclasson/vso-agent-tasks#10]
Hi,

First off great work with all of your extensions.
I was wondering if it would be possible instead of having a checkbox for the 'Make Release' flag, have a string with the release branch name. For example we have development and master. The build definition builds both branches but the development branch should have the prerelease tag at the end.

Thanks for the info

Franklin

**Comment by johanclasson** [comment]
Thanks! :)

First I would like to apologize for my late reply. The GitHub notifications got caught in my spam filter...

Now, would you think that adding a "Working folder" under the advanced group would solve your issue? That way you could point out the folders where the branches are mapped to. In your case, you will have to add the task once for each branch.
