### ISSUE TITLE
ApplySemanticVersioningToAssemblies - AssemblyInfo.vb compatibility

### ISSUE THREAD

**Issue by filippobottega** [johanclasson/vso-agent-tasks#11]
Hello,
  the ApplySemanticVersioningToAssemblies.ps1 script replaces version on AssemblyInfo.cs files.
  Is it possible to adapt the task to modify also AssemblyInfo.vb files?

  Thank you for your support,
    best regards, Filippo Bottega.

**Comment by johanclasson** [comment]
Sure, that's a great idea! :)

**Comment by filippobottega** [comment]
#12
