### ISSUE TITLE
Error on execution

### ISSUE THREAD

**Issue by perp1exed** [johanclasson/vso-agent-tasks#15]
Hi, thanks for your upload.

My error is below:
`A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - The certificate chain was issued by an authority that is not trusted.)`

I used the sa credentials but no joy.

Any help appreciated.

thanks.

**Comment by perp1exed** [comment]
Never mind, I had to set certification attribute to true - thx!

**Comment by johanclasson** [comment]
I'm glad you solved it! :)
