### ISSUE TITLE
DbUpMigration - Add Oracle support

### ISSUE THREAD

**Issue by sumo300** [johanclasson/vso-agent-tasks#23]
Oracle support is probably the next largest need from an implementation perspective (of the big, commercial DBMS's).  This would be a great next step for this plug-in which we have made a critical part of our current process.  Unfortunately, we have Oracle DBs, too.

**Comment by johanclasson** [comment]
I would be happy to support Oracle, although I have very limited experience working with them myself... I would need some help to make it happen!

**Comment by johanclasson** [comment]
Hm... I see now that there is no support for Oracle in DbUp yet. Some folks have tried to implement support for it but their PRs seems to have failed. Read more here: https://github.com/DbUp/DbUp/search?p=1&q=oracle&type=Issues&utf8=%E2%9C%93

I'm closing this issue, but am willing to open it up when DbUp supports Oracle DB.

**Comment by sumo300** [comment]
@johanclasson Agreed.  Hadn't noticed that!  Thanks for looking into it.

**Comment by sumo300** [comment]
Great news!
