### ISSUE TITLE
Scripts no longer update database

### ISSUE THREAD

**Issue by perp1exed** [johanclasson/vso-agent-tasks#24]
I understand a version has changed and the documentation also appears to show a new way of updating (using .Net code).

I am using the previous method whereby I have a sql project with sql scripts set to not "Build".

These scripts no longer are applied.

The message that I am seeing is: "No new scripts need to be executed - completing."

I have set journaling to be off.

Why are my scripts not being applied against the database?

I can confirm the script files are present in the working directory.

Any help appreciated.

thanks,

KS

**Comment by johanclasson** [comment]
What documentation do you refer to?

As far as I can see, everything is still working as intended. Can it be that your script path is pointing to a build-folder that has not got any scripts?

**Comment by perp1exed** [comment]
Sorry I got a little confused. The script folder does have scripts but it also has scripts in subfolders and those are not being executed. I have put all scripts in root now and it works. Thanks.

**Comment by johanclasson** [comment]
Ok, your issue is related to #22 then. Thanks for the information!
