### ISSUE TITLE
Error installing from VSTS marketplace

### ISSUE THREAD

**Issue by snavarropino** [johanclasson/vso-agent-tasks#31]
I get following error: 

Extension operation denied by event callback. Found

Thanks

**Comment by johanclasson** [comment]
VSTS have had similar hickups in the past. I invesitgated now by installing it to a "fresh" account, and all worked fine.

Can you please try again and see if it works now?

**Comment by snavarropino** [comment]
Sure, let me check

**Comment by snavarropino** [comment]
You were right, just installed

Thank you very much, hope this won't happen again
