### ISSUE TITLE
DbUp migration Failed due to error "Cannot bind argument to parameter 'Path' because it is null."

### ISSUE THREAD

**Issue by Vademag** [johanclasson/vso-agent-tasks#35]
Last night my deployments started to fail due to DbUp VSTS Task. I have an error

"Cannot bind argument to parameter 'Path' because it is null."

I see that DbUp library was updated to stable 4.0 version yesterday.

I attached log file from this task.
[tasklog_15.log](https://github.com/johanclasson/vso-agent-tasks/files/1914390/tasklog_15.log)

**Comment by johanclasson** [comment]
Thanks for letting me know!
