### ISSUE TITLE
DbUpMigration - Migrate to DbUp 4.0

### ISSUE THREAD

**Issue by johanclasson** [johanclasson/vso-agent-tasks#36]
Perhaps it is enough to point against NuGet package dbup-sqlserver.

**Comment by drwatson1** [comment]
Johan, hi!

Is there any chance to update the task to DbUp 4.2?

**Comment by johanclasson** [comment]
When 4.0 came out I tried upgrading but had som issues that scripts did not get executed in the same order anymore (I have tests that cover execution order). I did not have the time to investigate it further then, I you like you are more than welcome to take a look!

Out of curiosity, what feature in 4.2 is it you want that 3.5.5 does not have?

**Comment by drwatson1** [comment]
I use RunAlways to recreate views and run ordered groups to make sure it will run after update of db structure.

Ok. I'll try to do it and create a pr

**Comment by johanclasson** [comment]
Great. :) If you run into issues do not hesitate to send me a message and perhaps we can work it out together!

**Comment by drwatson1** [comment]
I've figured it out. [Here](https://github.com/DbUp/DbUp/issues/359) is the same problem described. I'll try to cope with it.

**Comment by johanclasson** [comment]
Nice. Great find!

**Comment by johanclasson** [comment]
There were some reflection issues, #51. I will try to investigate.

**Comment by johanclasson** [comment]
It very hard to read, yes, but I think it is: "ReflectionTypeLoadException. Unable to load one or more of the required types."

My guess is that it happens when that shunk of c# code is loaded and that some dll is missing.

Can be due to anything. Old PowerShell version? Old version of .NET Framework?

My plan was to try running the agent on a few different machines and see what happens.

If we can't reproduce this I'm thinking we could release the 4.0 version as a new mayor version of the tasks. That way it will not affect anybodys present setup.

**Comment by drwatson1** [comment]
Good idea. I'll try it too

**Comment by johanclasson** [comment]
I have released a 2.* version of the task where your contribution is included. Thanks again!
