### ISSUE TITLE
Add parameter for timeout

### ISSUE THREAD

**Issue by john-zzzz** [johanclasson/vso-agent-tasks#38]
DBUp supports the .WithExecutionTimeout(<TimeSpan>) property.  This should be mapped to an input variable of the task so that scripts which take longer than the default can be supported.

**Comment by johanclasson** [comment]
The task already dissables the execution timeout. Not with the method your are referring to, but through:
```
$configuration.ScriptExecutor.ExecutionTimeoutSeconds = 0
```
My idea was that one could use the overall build/release timeout. Du you think it is important to be able to specify timeouts on each script? Or is perhaps the timeout disabling as I have implemented it not working?

**Comment by johanclasson** [comment]
I am closing this since I do not think there is any issue with timeouts as currently configured.
