### ISSUE TITLE
Skip Variable Substitution

### ISSUE THREAD

**Issue by vjgn** [johanclasson/vso-agent-tasks#42]
Even when variable substitution is not configured, it appears this is still attempted. I end up with an error "variable XXX has no value defined". Even though my script has something matching the pattern of $XXX$, it should be ignored and executed, but this does not appear to be the case.

After reviewing the migration PowerShell code, I think we might have to call WithVariablesDisabled() if $VariableSubstitution set to $false. That way it is not attempted at all.

**Comment by johanclasson** [comment]
Looks like a great suggestion! I see you have already fixed it in a fork. Feel free to send a PR. I will perform some testing and then publish an updated version.

**Comment by vjgn** [comment]
Yes. I have fixed it in a fork and tested it successfully. I will send a PR shortly.
