### ISSUE TITLE
Account Service for Execution

### ISSUE THREAD

**Issue by xaviertop** [johanclasson/vso-agent-tasks#44]
Hi,

it is possible to configure a service account AD to execute DbUp Operation.
i don't want to use my account release to execute my script.

Thanks

Top Xavier

**Comment by johanclasson** [comment]
Sure!

Just configure your local build agent windows service to run with your service account, and use a connection string with trusted connection.

If you want a special account for just DbUp you will have to have a separate build agent just for that.

**Comment by xaviertop** [comment]
thanks for your answer.

it's not possible to add a service account in task configuration ? it will be more useful than service account. it will be a good enhancement.
