### ISSUE TITLE
DbUp Migration cannot find Scripts folder

### ISSUE THREAD

**Issue by Kosntantin** [johanclasson/vso-agent-tasks#47]
I have a pipeline on VSTS that automatically deploys my project. I would like to add DBUp to be ran as part of the deployement. I added a DbUp Migration task to the pipeline, but when it runs it says it cannot find my Scripts folder.  The script folder is inside my project. Any ideas how i can fix it?

![image](https://user-images.githubusercontent.com/42246943/45808077-3810bb80-bcc5-11e8-8ccf-7a2336359dcf.png)

**Comment by johanclasson** [comment]
Are the folder where your SQL-scripts are called Scripts, or have you named your linked artifact alias Scripts?

Just to rule out the obvious. Are you sure that your SQL-scripts are available for the build agent at that path?

My best guess is that you have entered a relative path such as `./Scripts` as the Script Folder Path for the DbUp-task. Try using the `[...]`-button to get a absolute path instead.

**Comment by Kosntantin** [comment]
![image](https://user-images.githubusercontent.com/42246943/45822314-74efa900-bceb-11e8-9084-3b970cd62c67.png)
This is my path. THe scripts are in the project in that folder and marked as embedded resources. Is it wrong?

**Comment by johanclasson** [comment]
Yes. Embedded resources are compiled intro your assembly. My DbUp extension only deals with regular SQL-files.

Have you tried the `[...]`-button?

**Comment by Kosntantin** [comment]
![image](https://user-images.githubusercontent.com/42246943/45840278-c2354000-bd16-11e8-86ba-852ec8275dc2.png)
This is what I see when I click it. How I can I make the folder available in there?

**Comment by johanclasson** [comment]
Here are a link to get your started.
https://docs.microsoft.com/en-us/azure/devops/pipelines/build/artifacts?view=vsts

Du you not have anyone at your office you can help you get started with Azure DevOps pipelines?
