### ISSUE TITLE
Support execution timeout

### ISSUE THREAD

**Issue by uchitha** [johanclasson/vso-agent-tasks#48]
DB up migrations by default run with a 30 second timeout. This might not be sufficient sometimes. However db up API provides a nice way to configure this.

`  var upgrader = DeployChanges.To.SqlDatabase(connectionString)                         .WithExecutionTimeout(TimeSpan.FromSeconds(180)).Build();
`

Would be useful to surface this up as a setting on the task.

Thank You.

**Comment by johanclasson** [comment]
I have used an (older) feature to dissable timout, and you can use the Timeout under Control Options for making the task time out.

I am closing this issue. Please reopen if your intended use case is different.

**Comment by snavarropino** [comment]
Hi, I am also suffering the timeout. Sometimes my scripts need more than 30 seconds to finish. @johanclasson you said: "I have used an (older) feature to disable timout". Is it released?

If I have understood well, the dbup task will not finish by timeout anymore. Am I wrong?

thanks!

**Comment by johanclasson** [comment]
DbUp will not timeout, see [this line](https://github.com/johanclasson/vso-agent-tasks/blob/0a6814fc8fcf503c9a75b156731a11d677a90a2b/DbUpMigration/task/Update-DatabaseWithDbUp.ps1#L158) for how it is implemented.

My guess is that you might be suffering from that something else times out. Have you set a timeout on the Control Options -> Timeout?

**Comment by johanclasson** [comment]
To verify, I just ran [this SQL-file](https://github.com/johanclasson/vso-agent-tasks/blob/master/DbUpMigration/test/sql/flat/05-longrunning.sql) against a Azure SQL DB using version 2.1.4 of the task, and it did not timeout.

**Comment by snavarropino** [comment]
Thanks! Let me check whether I am using the proper task version

**Comment by snavarropino** [comment]
Yes, I was using task v1. Now with v2 its working fine, sorry for the incovenience

**Comment by johanclasson** [comment]
Nice! Hopefully this can help someone else. I am glad I could be of help!
