### ISSUE TITLE
DbUp Migration - custom schema for journaling

### ISSUE THREAD

**Issue by CasperWSchmidt** [johanclasson/vso-agent-tasks#55]
We have (or going to have) a few databases on Azure. Each database will contain multiple schemas, one for each service needing a SQL DB. I would like to have each service completely isolated in its own schema - and at the same time avoid possible collisions - by having a _schemaVersion table in each schema instead of a single table in dbo for all services in the same database.
Default should probably still be dbo but an option to change it would be much appreciated.

**Comment by johanclasson** [comment]
Thanks for sending the PR!
