### ISSUE TITLE
Does this replace the need for the DbUp Console app?

### ISSUE THREAD

**Issue by MadMonkeyMan** [johanclasson/vso-agent-tasks#58]
Hi, I have created a DbUp console up in my DB project and want to use this task to deploy it. It seems though that this actually replaces my console app, or at least replaces my need to build, deploy, and then execute the console app. Is this correct?

**Comment by johanclasson** [comment]
As you have noticed, the DbUp Migration task replaces the need to roll your own project.

At least regarding running migrations against your test and production environments. But if you need something to run scripts locally you still need to do something creative.

**Comment by FarshanAhamed** [comment]
@johanclasson Is there any functionality similar to EnsureDatabase?

**Comment by johanclasson** [comment]
@FarshanAhamed: ~~Yes. It is on per default~~. Se [this line of code](https://github.com/johanclasson/vso-agent-tasks/blob/master/DbUpMigration/task/Update-DatabaseWithDbUp.ps1#L280).

I remembered it wrong. This is not on per default, nor can it be triggered. I created #72 to adress this.
