### ISSUE TITLE
Use Windows Account in Task Azure DevOps

### ISSUE THREAD

**Issue by xaviertop** [johanclasson/vso-agent-tasks#59]
Hi,

is it possible for a next enhancement to add a field for executing script by a windows account (like service account) ? 

Now, i use a powershell with dbup library to execute sql in a remote powershell script. 
it will be easy if i have this functionnality

thanks

**Comment by johanclasson** [comment]
Since that is only usable to machines connected to a domain I am reluctant to include this feature in the task. I think the best option for you is to set up agents (or deployment groups) where you run the windows service with the windows account that has access to the DB.

**Comment by xaviertop** [comment]
hi,

thanks for you answer. the aim to use a service account for executing the task is to manage right for this account to database. for example, i use a specifi account to INSERT/UPDATE/DELETE but not for alter/drop. So i have a release agent for executing only script and another release for executing alter/create/drop instructions for each application. if i use the windows service account, it will have too many privilege for all database.
