### ISSUE TITLE
DbUpMigration - Using deprecated task execution handler

### ISSUE THREAD

**Issue by tillig** [johanclasson/vso-agent-tasks#60]
Version 2.1.1 of the task when running on hosted agents in Azure DevOps now emits a warning:

```
2019-07-24T18:14:29.3623007Z ##[warning]Task 'UpdateDatabaseWithDbUp' (2.1.1) is using deprecated task execution handler. The task should use the supported task-lib: https://aka.ms/tasklib
```

I'm unclear at the moment what exactly needs to be fixed to address the warning.

**Comment by johanclasson** [comment]
Thanks for reporting this. When I made the task there were no task-lib. Using it would be quite straight forward.

**Comment by DecorteHannes** [comment]
Are there any plans to fix this warning?

**Comment by johanclasson** [comment]
Yes. But I have simply not got the time to do it right now. You are more than welcome to send a pull request!

**Comment by johanclasson** [comment]
Just stumbled upon this [blog post](https://blogs.blackmarble.co.uk/rfennell/2019/12/28/a-technique-for-porting-powershell-based-azure-devops-extensions-to-node-so-they-can-be-run-cross-platform-without-a-complete-re-write/). Can it be an option instead of using the PowerShell SDK?
