### ISSUE TITLE
Update-Database.ps requires VariableSubstitutionPrefix

### ISSUE THREAD

**Issue by andrewmacg123** [johanclasson/vso-agent-tasks#64]
Hi,

Great work on DbUp, thanks.

In the release that's come out today the VariableSubstitutionPrefix is now set as required, which is a breaking change for me. Is there another way I can set a blank prefix or should I now set one and update my vars?

Thanks

**Comment by francisdidden** [comment]
We are having the exact same problem. Could this change be reverted and/or added as a major version update? Since it's a beaking change, that might be appropriate.

Thank you

**Comment by johanclasson** [comment]
Thanks for reporting. I will send out a fix shortly!

**Comment by johanclasson** [comment]
There is now a new version 2.1.3 out that sets the VariableSubstitutionPrefix to not required.

**Comment by andrewmacg123** [comment]
Thanks for the quick turnaround Johan
