### ISSUE TITLE
DbUp migration -  Support for deployment to multiple database

### ISSUE THREAD

**Issue by Pooja-graafika** [johanclasson/vso-agent-tasks#73]
This works perfectly fine for a single database but for my requirement I need to deploy to multiple database instances in the same server, Please assist what changes can be done to achieve this.
#73

**Comment by sumo300** [comment]
Use multiple tasks that each target a different database on the same server and use the same set of files to execute the migration.

**Comment by Pooja-graafika** [comment]
> Use multiple tasks that each target a different database on the same server and use the same set of files to execute the migration.

But there can be only one variable DbUp.Database for the release pipeline and in that case having multiple tasks would not work right? PFA the image. Can I directly add the database name in the task itself directly instead of using it as a variable?Please assist.
![DbUp](https://user-images.githubusercontent.com/84763722/152160027-f1e0eef4-05d3-4afd-8601-9ffe880921b9.JPG)

**Comment by johanclasson** [comment]
Then use other variables for the tasks, or if you wish enter the DbName directly in the task.
